import { api } from "../api.js";
import { e, submitForm } from "../components.js";
import { reportPayload, operatorOptions } from "../model.js";
const alertBox = '<p class="error text-danger" role="alert" tabindex="-1"></p>';
const satellite = (id) => ({46320: 'NAPA-1 N', 48963: 'NAPA-2 N'}[id] ?? String(id ?? '-'));
const passName = (id) => ({1:'DayPass-1',2:'DayPass-2',3:'NightPass-1',4:'NightPass-2'}[id] ?? '-');
const shortname = (users, id) => { const u = users.find(u => String(u.rbac_id) === String(id)); return u?.rbac_shortname || u?.rbac_fullname || id || '-'; };
const showdate = (value) => { const d = new Date(`${value}T00:00:00Z`); return Number.isNaN(d.getTime()) ? value ?? '-' : `${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d.getUTCDay()]} ${String(d.getUTCDate()).padStart(2,'0')} ${['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][d.getUTCMonth()]} ${d.getUTCFullYear()}`; };
const header = (title, subtitle, icon, action = '') => `<header class="border-bottom pb-3 mb-4"><div class="d-flex align-items-center justify-content-between flex-wrap gap-2"><div><h1 class="h3 mb-1 d-flex align-items-center gap-2"><i class="bi bi-${icon}"></i>${title}</h1><p class="text-secondary mb-0">${subtitle}</p></div>${action}</div></header>`;
function modal(root, title, body, footer, danger = false) {
  const element = document.createElement('div');
  element.className = 'modal fade'; element.tabIndex = -1;
  element.setAttribute('aria-label', title);
  element.innerHTML = `<div class="modal-dialog ${danger ? '' : 'modal-lg'} modal-dialog-centered"><div class="modal-content"><div class="modal-header ${danger ? 'bg-danger text-white' : ''}"><h5 class="modal-title">${title}</h5>${danger ? '' : '<button type="button" class="btn btn-primary ms-2" id="copy-report"><i class="bi bi-clipboard"></i> Copy</button>'}<button type="button" class="btn-close ${danger ? 'btn-close-white' : ''}" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body">${alertBox}${body}</div><div class="modal-footer ${danger ? 'justify-content-center' : ''}">${footer}</div></div></div>`;
  root.append(element);
  const instance = new globalThis.bootstrap.Modal(element);
  element.addEventListener('hidden.bs.modal', () => { instance.dispose(); element.remove(); }, {once:true});
  instance.show(); return {element, instance};
}
export async function reports(root, user) {
  const [rows, lookups] = await Promise.all([api.get('/reports'),api.get('/lookups')]);
  root.querySelectorAll("table").forEach(table => { if(window.jQuery.fn.dataTable.isDataTable(table)) window.jQuery(table).DataTable().destroy(); });
  root.innerHTML = header('Report','Report Operate Satellite','ticket-detailed','<a href="#reports/new" class="btn btn-mono-primary"><i class="bi bi-plus-circle"></i> Add Report</a>') + `<div class="card border-0 shadow-sm"><div class="card-body p-3">${alertBox}<table id="missionTable" class="table table-striped table-bordered w-100"><thead class="table-dark"><tr>${['Flight No.','Date','Satellite','Pass','AOS-LOS','MD','Create BY','Action'].map((t,i)=>`<th ${i===0?'style="width:80px"':i===7?'class="text-center" style="width:200px"':'class="text-center"'}>${t}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${[r.sat_flight_pass,showdate(r.sat_report_date),satellite(r.norad_id),passName(r.sat_seq),`${r.sat_pass_aos} - ${r.sat_pass_los}`,shortname(lookups.users,r.sat_md),shortname(lookups.users,r.rbac_id)].map(v=>`<td class="text-center">${e(v)}</td>`).join('')}<td class="text-center">${String(r.rbac_id)===String(user?.rbac_id)?`<button class="btn btn-outline-info" data-view="${e(r.report_id)}" aria-label="View report"><i class="bi bi-eye"></i></button> <a href="/api/reports/${e(r.report_id)}/pdf" target="_blank" rel="noopener" class="btn btn-outline-warning" aria-label="PDF"><i class="bi bi-filetype-pdf"></i></a> <button class="btn btn-outline-danger" data-delete="${e(r.report_id)}" aria-label="Delete report"><i class="bi bi-trash"></i></button>`:'-'}</td></tr>`).join('')}</tbody></table></div></div>`;
  window.jQuery(root.querySelector('table')).DataTable({ordering:false,responsive:true,pageLength:25,columnDefs:[{targets:-1,orderable:false,searchable:false}]});
  root.onclick = async event => {
    const button = event.target.closest('[data-view],[data-delete]');
    if (!button) return;
    if (button.dataset.view) {try {await showReport(root,button.dataset.view,lookups);} catch(error){root.querySelector('[role="alert"]').textContent=error.message;}}
    if (button.dataset.delete) deleteReport(root,rows.find(r=>String(r.report_id)===button.dataset.delete),()=>reports(root,user));
  };

}
function deleteReport(root, r, after) {
  const {element,instance}=modal(root,'Confirm Delete',`<div class="text-center">ต้องการลบรายงาน Flight No. <strong>${e(r.sat_flight_pass)}</strong> ใช่หรือไม่</div>`,'<button type="button" class="btn btn-danger" id="confirm-delete">Delete</button><button class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>',true);
  element.querySelector('#confirm-delete').onclick=async(event)=>{event.target.disabled=true;try{await api.delete(`/reports/${r.report_id}`);element.addEventListener('hidden.bs.modal',after,{once:true});instance.hide();}catch(err){element.querySelector('[role="alert"]').textContent=err.message;event.target.disabled=false;}};
}
async function showReport(root,id,lookups) {
  const r=await api.get(`/reports/${encodeURIComponent(id)}`);
  const line=(label,value,classes='')=>`<div class="col-sm-12 ${classes}"><b>${label} :</b> ${e(value??'-')}</div>`;
  const logs=(rows,kind)=>rows?.length?`<ul>${rows.map(m=>`<li><b>${e(m[`${kind}_name`])}</b><br>${kind==='mission'?'รายละเอียด':'การดำเนินการแก้ไข'}: ${e(m[`log${kind}_name`]??'-')}<br>ผลการปฏิบัติ: ${e(m[`log${kind}_result`]??'-')}</li>`).join('')}</ul>`:'<div>-</div>';
  const orbit=r.altitude_km==null?'<div>-</div>':`<ul><li><b>${e(r.orbit_epoch_date)} ${e(r.orbit_epoch_time)}</b><br>${[['altitude_km','Altitude','km'],['inclination_deg','Inclination','deg'],['orbital_period_min','Orbital Period','min'],['velocity_km_s','Velocity','km/s']].map(([k,l,u])=>`<b>${l} : </b>${r[k]==null?'-':e(Number(r[k]).toFixed(2))} ${u}<br>`).join('')}</li></ul>`;
  const body=`<div class="container-sm"><div class="container mt-3 mb-3"><div class="row" id="report-copy-content">${line('Satellite',satellite(r.norad_id))}${line('Pass',passName(r.sat_seq))}${line('Flight Pass No.',r.sat_flight_pass)}${line('Date (UTC)',showdate(r.sat_report_date))}${line('Time (UTC)',`AOS ${r.sat_pass_aos} LOS ${r.sat_pass_los}`)}${line('Duration',`${r.sat_pass_duration_min} min ${r.sat_pass_duration_sec} sec`)}${line('Max Elevation',`${r.sat_max_el} EL.`,'mb-3')}<div class="col-sm-12 mb-3"><b>Orbits Detail :</b>${orbit}</div><div class="col-sm-12"><b>Mission Detail :</b>${logs(r.missions,'mission')}</div>${line('Ground Station',r.sat_gsostatus)}${line('MCS System',r.sat_mcs)}${line('PDHU Free Space',`${r.sat_pdhufreespace} GB`)}${line('Last Image ID',r.sat_lastimg,'mb-3')}<div class="col-sm-12 mb-3"><b>Trouble Detail :</b>${logs(r.troubles,'trouble')}</div>${line('การดำเนินการ Next Pass',r.sat_next_pass,'mb-3')}${['md','fmo','gso'].map(k=>line(k.toUpperCase(),shortname(lookups.users,r[`sat_${k}`]))).join('')}${r.sat_note?line('หมายเหตุ',r.sat_note,'mt-3'):''}<div class="col-sm-12 mt-3"><details><summary>Status &amp; Notes</summary>${line('Napa Approaching',({1:'ใช้งานได้ปกติ',2:'ใช้งานไม่ได้ระหว่างพาส',3:'ใช้งานไม่ได้'}[r.approaching]??r.approaching))}${line('Orbit fetched at',r.orbit_fetched_at)}</details></div></div></div></div>`;
  const {element}=modal(root,'Satellite Report Detail',body,'<button class="btn btn-secondary" data-bs-dismiss="modal">Close</button>');
  element.querySelector('#copy-report').onclick=async(event)=>{const b=event.currentTarget;try{await navigator.clipboard.writeText(element.querySelector('#report-copy-content').innerText);b.innerHTML='<i class="bi bi-check-circle"></i> คัดลอกแล้ว';}catch{element.querySelector('[role="alert"]').textContent='ไม่สามารถคัดลอกข้อความได้';}};
}
export async function reportDetail(root,id,user) { await reports(root,user); await showReport(root,id,await api.get('/lookups')); }

const optionsHTML=(options,value='',placeholder='')=>(placeholder?`<option value="" disabled ${value===''?'selected':''}>${e(placeholder)}</option>`:'')+options.map(o=>{const[v,l]=Array.isArray(o)?o:[o,o];return `<option value="${e(v)}" ${String(value)===String(v)?'selected':''}>${e(l)}</option>`;}).join('');
function control(name,label,{options,placeholder='',value='',width=3,type='text',required=true}={}) {
 const attrs=`id="${e(name)}" name="${e(name)}" ${required?'required':''}`;
 return `<div class="col-12 col-md-${width}"><label for="${e(name)}" class="form-label">${e(label)} ${required?'<span class="text-danger">*</span>':''}</label>${options?`<select class="form-select" ${attrs}>${optionsHTML(options,value,placeholder)}</select>`:type==='textarea'?`<textarea class="form-control" ${attrs} rows="3" maxlength="255" placeholder="${e(placeholder)}">${e(value)}</textarea>`:`<input class="form-control" ${attrs} type="text" value="${e(value)}" maxlength="255" placeholder="${e(placeholder)}" autocomplete="off">`}</div>`;
}
const section=(number,title,body,actions='')=>`<div class="mb-4"><div class="d-flex align-items-center justify-content-between mb-3"><div class="d-flex align-items-center gap-2"><span class="badge bg-mono-subtle text-secondary border border-mono-subtle">${number}</span><h2 class="h6 mb-0">${title}</h2></div>${actions}</div>${body}</div>`;
function logSection(kind,number,title) {return section(number,title,`<div class="table-responsive"><table class="table table-bordered align-middle"><thead class="table-light"><tr><th class="text-center" style="width:60px">No.</th><th style="width:${kind==='mission'?400:220}px">${kind==='mission'?'ภารกิจ':'ข้อขัดข้อง'} <span class="text-danger">*</span></th><th ${kind==='mission'?'style="width:160px"':''}>${kind==='mission'?'รายละเอียด':'การแก้ไข'}</th><th style="width:160px;${kind==='mission'?'white-space:nowrap':''}">${kind==='mission'?'ผลการปฏิบัติ':'ผลการแก้ไข'} <span class="text-danger">*</span></th></tr></thead><tbody id="${kind}-rows"></tbody></table></div>${kind==='trouble'?`<div class="row">${control('sat_next_pass','การดำเนินการ Next Pass',{width:12,type:'textarea',placeholder:'งานที่ต้องทำในพาสถัดไป'})}</div>`:''}`,`<div><button type="button" class="btn btn-outline-success btn-sm" data-add="${kind}"><i class="bi bi-plus-circle me-1"></i>Add</button> <button type="button" class="btn btn-outline-danger btn-sm" data-remove="${kind}"><i class="bi bi-dash-circle me-1"></i>Remove</button></div>`);}
export async function newReport(root,selectedPass) {
 const [passes,lookups]=await Promise.all([api.get('/passes'),api.get('/lookups')]);
 const chosen=passes.find(p=>String(p.id)===String(selectedPass));
 const satellites=[...new Set(['46320','48963',...passes.map(p=>String(p.satellite_id))])].map(id=>[id,satellite(id)]);
 const divider='<hr class="text-body-tertiary">';
 root.innerHTML=header('Create Mission','บันทึกภารกิจดาวเทียม ประจำพาส/รอบปฏิบัติการ','rocket-takeoff')+`<div class="card border-0 shadow-sm"><div class="card-header"><div class="d-flex align-items-center gap-2"><i class="bi bi-ui-checks-grid"></i><span class="fw-semibold">Mission Details Form</span></div></div><div class="card-body"><form id="report-form" class="needs-validation">${alertBox}`+[
 section(1,'Pass Information',`<div class="row g-3">${control('norad_id','Satellite',{options:satellites,placeholder:'-- Satellite --',value:chosen?.satellite_id??''})}${control('sat_seq','Satellite Pass',{options:[[1,'DayPass 1'],[2,'DayPass 2'],[3,'NightPass 1'],[4,'NightPass 2']],placeholder:'-- Satellite Pass --'})}${control('pass_id','AOS-LOS (UTC)',{options:[],placeholder:'-- AOS-LOS (UTC) --'})}${control('sat_flight_pass','Flight pass',{placeholder:'เช่น XXX/2026'})}</div>`),
 logSection('mission',2,'Mission & Results'),
 section(3,'Systems Status',`<div class="row g-3">${control('sat_gsostatus','Ground Station',{options:['Normal','Not Active'],value:'Normal'})}${control('sat_mcs','Mission Control System',{options:['Not Active','Active'],value:'Not Active'})}${control('sat_pdhufreespace','PDHU-FreeSpace (GB)')}${control('sat_lastimg','Last-Img (Session ID)',{placeholder:'เช่น 1911'})}</div>`),
 logSection('trouble',4,'Troubleshooting'),
 section(5,'Responsible Staff',`<div class="row g-3">${['md','fmo','gso'].map(role=>control(`sat_${role}`,role.toUpperCase(),{width:4,placeholder:`-- เลือก ${role.toUpperCase()} --`,options:operatorOptions(lookups.users,role).map(([id,label])=>[id,shortname(lookups.users,id)||label])})).join('')}</div>`),
 section(6,'Status & Notes',`<div class="row g-3">${control('approaching','Napa Approaching',{width:12,value:'1',options:[[1,'ใช้งานได้ปกติ'],[2,'ใช้งานไม่ได้ระหว่างพาส'],[3,'ใช้งานไม่ได้']]})}${control('sat_note','หมายเหตุ',{width:12,type:'textarea',placeholder:'บันทึกเพิ่มเติม'})}</div>`)
 ].join(divider)+`<div class="d-flex gap-2"><button type="submit" class="btn btn-outline-success" ${passes.length?'':'disabled'}><i class="bi bi-check2-circle me-1"></i> Create</button><a class="btn btn-outline-danger" href="#reports"><i class="bi bi-arrow-left-short me-1"></i> Back</a></div>${passes.length?'':'<p class="text-secondary mt-3">ยังไม่มีพาสดาวเทียม กรุณาจัดเตรียมข้อมูลพาสก่อนสร้างรายงาน</p>'}</form></div></div>`;
 const updatePasses=()=>{const select=root.querySelector('#pass_id'),matching=passes.filter(p=>String(p.satellite_id)===root.querySelector('#norad_id').value).sort((a,b)=>`${a.aos_date_utc} ${a.aos_time_utc}`.localeCompare(`${b.aos_date_utc} ${b.aos_time_utc}`));select.innerHTML=optionsHTML([], '', '-- AOS-LOS (UTC) --');for(const date of [...new Set(matching.map(p=>p.aos_date_utc))]){const group=document.createElement('optgroup');group.label=date;group.innerHTML=optionsHTML(matching.filter(p=>p.aos_date_utc===date).map(p=>[p.id,`${p.aos_time_utc} - ${p.los_time_utc}`]),selectedPass??'');select.append(group);} select.disabled=!matching.length;};
 root.querySelector('#norad_id').onchange=()=>{selectedPass='';updatePasses();};updatePasses();
 const addRow=(kind,focus=true)=>{const target=root.querySelector(`#${kind}-rows`),row=document.createElement('tr'),index=target.children.length+1;row.innerHTML=`<td class="text-center">${index}</td><td><select class="form-select" name="${kind}_id[]" required aria-label="${kind==='mission'?'ภารกิจ':'ข้อขัดข้อง'} ${index}">${optionsHTML(lookups[`${kind}s`].map(r=>[r[`${kind}_id`],kind==='trouble'?`(${lookups.subsystems.find(s=>String(s.sub_id)===String(r.sub_id))?.sub_name??'-'}) ${r.trouble_name}`:r.mission_name]),'',kind==='mission'?'-- Mission --':'-- เลือกปัญหา --')}</select></td><td><input class="form-control" name="log${kind}_name[]" maxlength="255" aria-label="${kind==='mission'?'รายละเอียด':'การแก้ไข'} ${index}" placeholder="${kind==='mission'?'รายละเอียดเพิ่มเติม':'ดำเนินการแก้ไข'}" autocomplete="off"></td><td><select class="form-select" name="log${kind}_result[]" required aria-label="ผลการปฏิบัติ ${index}">${optionsHTML(['เรียบร้อย','ไม่เรียบร้อย','ดำเนินการต่อ'],'','-- Result --')}</select></td>`;if(kind==='mission')row.querySelectorAll('.form-select,.form-control').forEach(input=>{input.style.fontSize='0.9rem';});target.append(row);if(focus)row.querySelector('select').focus();};
 root.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addRow(b.dataset.add));
 root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const target=root.querySelector(`#${b.dataset.remove}-rows`);if(b.dataset.remove==='mission'&&target.children.length<=1){alert('ต้องมีอย่างน้อย 1 mission');return;}target.lastElementChild?.remove();});addRow('mission',false);
 submitForm(root.querySelector('form'),async(form)=>{const result=await api.post('/reports',reportPayload(form));location.hash=`reports/${result.report_id}`;});
}

